# Preface {.unnumbered}

\vspace{-10mm}

Welcome to the second edition of Introductory Statistics for the Life and Biomedical Sciences.

This text is intended for undergraduate and graduate students interested in careers in biology or medicine, and may also be profitably read by students of public health or medicine.  It covers many of the traditional introductory topics in statistics, in addition to discussing some newer methods being used in molecular biology. 

Statistics has become an integral part of research in medicine and biology, and the tools for summarizing data and drawing inferences from data are essential both for understanding the outcomes of studies and for incorporating measures of uncertainty into that understanding.  An introductory text in statistics for students who will work in medicine, public health, or the life sciences should be more than simply the usual introduction, supplemented with an occasional example from biology or medical science. By drawing the majority of examples and exercises in this text from published data, we hope to convey the value of statistics in medical and biological research. In cases where examples draw on important material in biology or medicine, the problem statement contains the necessary background information. 

Computing is an essential part of the practice of statistics.  Nearly everyone entering the biomedical sciences will need to interpret the results of analyses conducted in software; many will also need to be capable of conducting such analyses. The text and associated materials separate those two activities to allow students and instructors to emphasize either or both skills. The text discusses the important features of figures and tables used to support an interpretation, rather than the process of generating such material from data. This allows students whose main focus is understanding statistical concepts not to be distracted by the details of a particular software package. In our experience, however, we have found that many students enter a research setting after only a single course in statistics. These students benefit from a practical introduction to data analysis that incorporates the use of a statistical computing language. The` self-paced learning labs associated with the text provide such an introduction; these are described in more detail later in this preface. 

<!---
The datasets used in this book are available via the \textsf{R} \texttt{openintro} package available on CRAN\footnote{Diez DM, Barr CD, \c{C}etinkaya-Rundel M. 2012. \texttt{openintro}: OpenIntro data sets and supplement functions. \urlwofont{http://cran.r-project.org/web/packages/openintro}.}  and the \textsf{R} \texttt{oibiostat} package available via \href{https://github.com/OI-Biostat/oi_biostat_data}{GitHub}.

-->

## Textbook overview {.unnumbered .unlisted}

The text is organized into chapters:

- **1. Introduction to data.** Data structures, basic data collection principles, numerical and graphical summaries, and exploratory data analysis.
- **2. Probability.** The basic principles of probability.
- **3. Distributions of random variables.** Introduction to random variables, distributions of discrete and continuous random variables, and distributions for pairs of random variables.
**4. Foundations for inference.** General ideas for statistical inference in the context of estimating a population mean.
**5. Inference for numerical data.** Inference for one-sample and two-sample means with the $t$-distribution, power calculations for a difference of means, and ANOVA.
**6. Simple linear regression.* An introduction to linear regression with a single explanatory variable, evaluating model assumptions, and inference in a regression context.
**7. Multiple linear regression.** General multiple regression model, categorical predictors with more than two values, interaction, and model selection.
**8. Inference for categorical data.** Inference for single proportions, inference for two or more groups, and outcome-based sampling.
**9. Logistic regression.** Simple and multiple logistic regression, inference for parameters, estimating prediction error.



\clearpage

Each chapter ends with a review which contains a chapter summary as well as a list of key terms introduced in the chapter.
If you're not sure what some of these terms mean, we recommend you go back in the text and review their definitions.
We purposefully present them in alphabetical order, instead of in order of appearance, so they will be a little more challenging to locate.
However, you should be able to easily spot them as **bolded text**.

## Changes for the second edition {.unnumbered .unlisted}

In development


## Examples and exercises {.unnumbered .unlisted}

Examples are provided to establish an understanding of how to apply methods.

::: {.workedexample data-latex=""}
This is an example.
When a question is asked here, where can the answer be found?

------------------------------------------------------------------------

The answer can be found here, in the solution section of the example!
:::

When we think the reader is ready to try determining a solution on their own, we frame it as Guided Practice.

::: {.guidedpractice data-latex=""}
The reader may check or learn the answer to any Guided Practice problem by reviewing the full solution in a footnote.[^preface-1]
:::

[^preface-1]: Guided Practice problems are intended to stretch your thinking, and you can check yourself by reviewing the footnote solution for any Guided Practice.

Exercises are also provided at the end of each chapter.
Solutions are given for odd-numbered exercises in [Appendix -@sec-exercise-solutions].

\clearpage

## Datasets and their sources {.unnumbered .unlisted}

A large majority of the datasets used in the book can be found in various R packages.
Each time a new dataset is introduced in the narrative, a reference to the package like the one below is provided.
Many of these datasets are in the [**openintro**](http://openintrostat.github.io/openintro) R package that contains datasets used in [OpenIntro](https://www.openintro.org/)'s open-source textbooks.[^preface-2]

[^preface-2]: Mine Çetinkaya-Rundel and David Diez and Andrew Bray and Albert Y. Kim and Ben Baumer and Chester Ismay and Nick Paterno and Christopher Barr (2024).
    openintro: Datasets and Supplemental Functions from 'OpenIntro' Textbooks and Labs.
    R package version 2.5.0.
    <https://github.com/openintrostat/openintro>.

::: {.data data-latex=""}
The [`textbooks`](http://openintrostat.github.io/openintro/reference/textbooks.html) data can be found in the [**openintro**](http://openintrostat.github.io/openintro) R package.
:::

The datasets used throughout the book come from real sources like opinion polls and scientific articles, except for a handful of cases where we use toy data to highlight a particular feature or explain a particular concept.
References for the sources of the real data are provided at the end of the book.

## Computing with R {.unnumbered .unlisted}

The narrative and the exercises in the book are computing language agnostic, however while it's possible to learn about modern statistics without computing, it's not possible to apply it.
Therefore, we invite you to navigate the concepts you have learned in each part using the interactive R tutorials and the R labs that are included at the end of each part.

### Interactive R tutorials {.unnumbered .unlisted}

The self-paced and interactive R tutorials were developed using the [learnr](https://rstudio.github.io/learnr/index.html) R package, and only an internet browser is needed to complete them.

::: {.alltutorials data-latex=""}
Each part comes with a tutorial comprised of 4-10 lessons and listed like this.
:::

::: {.singletutorial data-latex=""}
Each of these lessons is listed like this.
:::

::: {.content-visible when-format="pdf"}
You can access the full list of tutorials supporting this book <https://openintrostat.github.io/ims-tutorials>.
:::

::: {.content-visible when-format="html"}
You can access the full list of tutorials supporting this book [here](https://openintrostat.github.io/ims-tutorials).
:::

### R labs {.unnumbered .unlisted}

Once you feel comfortable with the material in the tutorials, we also encourage you to apply what you've learned via the computational labs that are also linked at the end of each part.
The labs consist of data analysis case studies, and they require access to [R](https://cran.r-project.org/) and [RStudio](https://posit.co/products/open-source/rstudio/).
The first lab includes installation instructions.
If you'd rather not install the software locally, you can also try [Posit Cloud](https://posit.cloud/) for free.

::: {.singlelab data-latex=""}
Labs for each part are listed like this.
:::

::: {.content-hidden unless-format="pdf"}
You can access the full list of labs supporting this book at [openintro.org/go?id=ims-r-labs](https://www.openintro.org/go?id=ims-r-labs).
:::

::: {.content-visible when-format="html"}
You can access the full list of labs supporting this book [here](https://www.openintro.org/go?id=ims-r-labs).
:::

\clearpage

## OpenIntro, online resources, and getting involved {.unnumbered .unlisted}

OpenIntro is an organization focused on developing free and affordable education materials. We encourage anyone learning or teaching statistics to visit [openintro.org](http://www.openintro.org) and to get involved.

All OpenIntro resources are free and anyone is welcomed to use these online tools and resources with or without this textbook as a companion.

We value your feedback.
If there is a part of the project you especially like or think needs improvement, we want to hear from you.
For feedback on this specific book, you can open an issue on the GitHub repository of the book at [github.com/openintrostat/ims](https://github.com/openintrostat/ims).
You can also provide feedback on this book or any other OpenIntro resource via our contact form at [openintro.org](https://www.openintro.org/form/?f=contact). 

## Acknowledgements {.unnumbered .unlisted}

The *OpenIntro* project would not have been possible without the dedication and volunteer hours of all those involved, and we hope you will join us in extending a huge *thank you* to all those who volunteer with OpenIntro.

This text has benefited from feedback from Morgan Breitmeyer, Andrea Foulkes, Raji Balasubramanian, Diane Dolezel, Barbara Elashoff, Andrea Foulkes, Curry Hilton, Joe Hogan, Mike Jiroutek, Michael Parzen, Kevin Rader and Alice Zhao as well as the many excellent teaching fellows at Harvard College who assisted in courses using the book.  The cover design was provided by Pierre Baduel. David Diez provided assistance with editing and formatting the first edition, and Mine Çetinkaya-Rundel provided guidance in using Quarto.

We would like to also thank the developers of the open-source tools that make the development and authoring of this book possible, e.g., [Quarto](https://quarto.org/), [tidyverse](https://tidyverse.org/), [tidymodels](https://tidymodels.org/), and [icons8](http://icons8.com/).

We are also grateful to the many teachers, students, and other readers who have helped improve OpenIntro resources through their feedback.
