
*Discrete random variables*

<!--- new --->

**The minimum of 2 dice.** Suppose a random process consists of rolling two dice. Using the information in @tbl-sum-two-dice find the distribution of the minimum value of the two faces.



<!--- OS4 3.29 -->

**College Smokers.**  At a university, 13% of 
students smoke.

  a. Calculate the expected number of smokers in a random sample of 100 students 
from this university.

  b. The university gym opens at 9 am on Saturday mornings. One Saturday morning 
at 8:55 am there are 27 students outside the gym waiting for it to open. Should 
you use the same approach from part (a) to calculate the expected number of 
smokers among these 27 students?

<!--- OS4 3.30 -->

**Ace of clubs wins.**  Consider the following card game with a well-shuffled deck of cards. If you draw a red card, you win nothing. If 
you get a spade, you win \$5. For any club, you win \$10 plus an extra \$20 for 
the ace of clubs.

  a. Create a probability model for the amount you win at this game. Also, find 
the expected winnings for a single game and the standard deviation of the 
winnings.

  b. What is the maximum amount you would be willing to pay to play this game? 
Explain your reasoning.

<!--- OS4 3.31 --->

**Hearts win.** In a new card game, you start
with a well-shuffled full deck and draw 3 cards without replacement.
If you draw 3 hearts, you win \$50. If you draw 3 black cards, you win \$25. For any other draws, you 
win nothing.

  a. Create a probability model for the amount you win at this game, and find 
the expected winnings. Also compute the standard deviation of this distribution.

  b. If the game costs \$5 to play, what would be the expected value and 
standard deviation of the net profit (or loss)? \textit{(Hint: 
profit = winnings $-$ cost; $X-5$)}

  c. If the game costs \$5 to play, should you play this game? Explain.
  
<!--- OS4 3.34 --->

**Baggage fees.**  An airline charges the following 
baggage fees: \$25 for the first bag and \$35 for the second. Suppose 54\% of 
passengers have no checked luggage, 34\% have one piece of checked luggage and 
12\% have two pieces. We suppose a negligible portion of people check more than 
two bags.

  a. Build a probability model, compute the average revenue per passenger, and 
compute the corresponding standard deviation.

  b. About how much revenue should the airline expect for a flight of 120 
passengers? With what standard deviation? Note any assumptions you make and if 
you think they are justified.

<!--- oibiostat 3.5 --->

**Gull clutch size.**  Large black-tailed gulls usually lay one to three eggs, and rarely have a fourth egg clutch. It is thought that clutch sizes are effectively limited by how effectively parents can incubate their eggs. Suppose that on average, gulls have a 25\% of laying 1 egg, 40\% of laying 2 eggs, 30\% chance of laying 3 eggs, and 5\% chance of laying 4 eggs.

  a. Calculate the expected number of eggs laid by a random sample of 100 gulls. 
		
  b. Calculate the standard deviation of the number of eggs laid by a random sample of 100 gulls.
  
  
<!--- OS4  3.35 --->

**American roulette** The game of American  roulette involves spinning a wheel with 38 slots: 18 red, 18 black, and 2 green. 
A ball is spun onto the wheel and will eventually land in a slot, where each slot 
has an equal chance of capturing the ball. Gamblers can place bets on red or 
black. If the ball lands on their color, they double their money. If it lands on 
another color, they lose their money. Suppose you bet \$1 on red. What's the 
expected value and standard deviation of your winnings?

<!--- OS4 3.36 -->

**European roulette** The game of European 
roulette involves spinning a wheel with 37 slots: 18 red, 18 black, and 1 green. 
A ball is spun onto the wheel and will eventually land in a slot, where each slot 
has an equal chance of capturing the ball. Gamblers can place bets on red or 
black. If the ball lands on their color, they double their money. If it lands on 
another color, they lose their money.

  a. Suppose you play roulette and bet \$3 on a single round. What is the 
expected value and standard deviation of your total winnings?

  b. Suppose you bet \$1 in three different rounds. What is the expected value 
and standard deviation of your total winnings?

  c. How do your answers to parts (a) and (b) compare? What does this say about 
the riskiness of the two games?

  
*Continuous random variables*  

<!--- OS4 3.37 --->

**Cat weights**  The histogram shown below represents 
the weights (in kg) of 47 female and 97 male cats. ^[W. N. Venables and B. D. Ripley. 
Modern Applied Statistics with S, Fourth edition. \url{www.stats.ox.ac.uk/pub/MASS4}. New York: Springer, 2002.] 

  a. What fraction of these cats weigh less than 2.5 kg?

  b. What fraction of these cats weigh between 2.5 and 2.75 kg?
  
  d. What fraction of these cats weigh between 2.75 and 3.5 kg?

```{r}
library(openintro)

# load MASS for data ------------------------------------------------
library(MASS)
data(cats)

# histogram of weights ----------------------------------------------

hist(cats$Bwt, breaks = seq(2, 4, 0.25), ylim = c(0, 35), 
     xlab = "Body weight",
     ylab = "Count",
     col = COL[1], main = "", 
     axes = FALSE)
axis(1)
axis(2, at = seq(0,40,10))

```
<!--- add distributions from NHANESA -->

*Sums of random variables*

<!--- OS4 3.44 --->

**Scooping ice cream.** Ice cream usually comes in 1.5 
quart boxes (48 fluid ounces), and ice cream scoops hold about 2 ounces. 
However, there is some variability in the amount of ice cream in a box as well as 
the amount of ice cream scooped out. We represent the amount of ice cream in the 
box as $X$ and the amount scooped out as $Y$. Suppose these random variables have 
the following means, standard deviations, and variances:
| Variable | Mean | SD   | Variance |
|:----------|-----:|----:|---------:|
| $X$       | 48   | 1   | 1.0000   |
| $Y$       | 2    | 0.25| 0.0625   |
  a. An entire box of ice cream, plus 3 scoops from a second box is served at a 
party. How much ice cream do you expect to have been served at this party? What 
is the standard deviation of the amount of ice cream served?

  b. How much ice cream would you expect to be left in the box after scooping 
out one scoop of ice cream? That is, find the expected value of $X-Y$. What is 
the standard deviation of the amount left in the box?

  c. Using the context of this exercise, explain why we add variances when we 
subtract one random variable from another.

<!--- OS4 3.45 --->

**Variance of a mean, I.**  Suppose we have independent observations $X_1$ and $X_2$ from
a distribution with mean $\mu$ and standard deviation $\sigma$.
What is the variance of the mean of the two values:
$\frac{X_1 + X_2}{2}$?

<!--- OS4 3.46 --->

**Variance of a mean, II.**  Suppose we have 3 independent observations
$X_1$, $X_2$, $X_3$ from
a distribution with mean $\mu$ and standard deviation $\sigma$.
What is the variance of the mean of these 3 values:
$\frac{X_1 + X_2 + X_3}{3}$?

<!---OS4 3.47 --->

**Variance of a mean, III.**  Suppose we have $n$ independent observations
$X_1$, $X_2$, ..., $X_n$ from
a distribution with mean $\mu$ and standard deviation $\sigma$.
What is the variance of the mean of these $n$ values:
$\frac{X_1 + X_2 + \dots + X_n}{n}$?

